[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://kdrama-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/classement_kdramas-1.html"
  status = 200
